### PR TITLE
Added . idea file

### PR DESCRIPTION
**Pull request by Servelec-Jack-Hurst**

### CODE REVIEW

**Review by servelec-jeremy-hotham — CHANGES_REQUESTED** [review]
Bad code, whole things garbage

**Comment by Servelec-Jack-Hurst** [comment]
u tryinto start a fite m8! Il hv u

**Comment by servelec-jeremy-hotham** [comment]
I think the picture addition makes the code a lot better.

**Review by Servelec-Jack-Hurst — COMMENTED** [review]
Can't even see it

**Comment by servelec-jeremy-hotham** [comment]
Yeah it's probably a browser thing or whatever

**Comment by servelec-jeremy-hotham** [comment]
I'm going to approve the changes

**Review by servelec-jeremy-hotham — APPROVED** [review]

**Pull request merged**
